### ===================== USUÁRIOS =====================

### Criar usuário
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nome": "rafa",
  "email": "leoo@email.com",
  "senha": "1243456"
}

###

### Listar usuários
GET http://localhost:3000/api/usuarios
Accept: application/json

###

### Buscar usuário por ID
GET http://localhost:3000/api/usuarios/5
Accept: application/json

###

### Editar usuário
PUT http://localhost:3000/api/usuarios/5
Content-Type: application/json

{
  "nome": "Leo Atualizado",
  "email": "leo.novo@email.com"
}

###

### Deletar usuário
DELETE http://localhost:3000/api/usuarios/1
Accept: application/json

### ===================== EVENTOS =====================

### ===== EVENTOS =====

# Criar evento
POST http://localhost:3000/api/eventos
Content-Type: application/json

{
  "titulo": "Festa do Pijama",
  "descricao": "Com pipoca e guerra de travesseiro",
  "imagem_url": "https://exemplo.com/imagem.jpg",
  "criador_id": 6
}

###

# Listar todos os eventos
GET http://localhost:3000/api/eventos
Accept: application/json

###

# Buscar evento por ID
GET http://localhost:3000/api/eventos/19
Accept: application/json

###

# Editar evento
PUT http://localhost:3000/api/eventos/19
Content-Type: application/json

{
  "titulo": "Festa Junina Atualizada",
  "descricao": "Descrição atualizada do evento",
  "imagem_url": "https://exemplo.com/log.jpg"
}

###

# Deletar evento
DELETE http://localhost:3000/api/eventos/1

###

# Obter dashboard do evento
GET http://localhost:3000/api/eventos/24/dashboard
Accept: application/json

###
### ===================== INSCRIÇÕES =====================

### Criar inscrição
POST http://localhost:3000/api/inscricoes
Content-Type: application/json

{
  "usuario_id": 6,
  "evento_id": 24,
  "nome_participante": "Fulano da Silva",
  "idade_participante": 22
}


###

### Listar inscrições
GET http://localhost:3000/api/inscricoes
Accept: application/json

###

### Buscar inscrição por ID
GET http://localhost:3000/api/inscricoes/8
Accept: application/json

###

### Editar inscrição
PUT http://localhost:3000/api/inscricoes/8
Content-Type: application/json

{
  "usuario_id": 6,
  "evento_id": 24,
  "nome_participante": "Doutor Silva",
  "idade_participante": 33
}

###

### Deletar inscrição
DELETE http://localhost:3000/api/inscricoes/8
Accept: application/json
