CREATE TABLE if not exists "usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" VARCHAR(100),
  "sobrenome" VARCHAR(100),
  "email" VARCHAR(100) UNIQUE NOT NULL,
  "senha" VARCHAR(255) NOT NULL,
  "cpf" VARCHAR(14) UNIQUE,
  "data_nascimento" DATE,
  "genero" VARCHAR(20),
  "criado_em" TIMESTAMP DEFAULT now()
);

CREATE TABLE if not exists "organizadores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_entidade" VARCHAR(100),
  "usuario_id" INT REFERENCES "usuarios" ("id")
);

CREATE TABLE if not exists "eventos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" VARCHAR(100) NOT NULL,
  "descricao" TEXT,
  "data" TIMESTAMP,
  "local" VARCHAR(255),
  "imagem_capa" VARCHAR(255),
  "organizador_id" INT REFERENCES "organizadores" ("id"),
  "criado_em" TIMESTAMP DEFAULT now()
);

CREATE TABLE if not exists "ingressos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evento_id" INT REFERENCES "eventos" ("id"),
  "usuario_id" INT REFERENCES "usuarios" ("id"),
  "tipo" VARCHAR(50),
  "preco_pago" DECIMAL(10,2),
  "status" VARCHAR(20) DEFAULT 'pendente',
  "data_compra" TIMESTAMP DEFAULT now(),
  "codigo_ticket" VARCHAR(50) UNIQUE
);

CREATE TABLE if not exists "pagamentos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ingresso_id" INT REFERENCES "ingressos" ("id"),
  "valor" DECIMAL(10,2),
  "forma_pagamento" VARCHAR(30),
  "status" VARCHAR(20) DEFAULT 'pendente',
  "data_pagamento" TIMESTAMP
);

CREATE TABLE if not exists "relatorio_vendas_evento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evento_id" INT REFERENCES "eventos" ("id"),
  "nome_comprador" VARCHAR(100),
  "idade_comprador" INT,
  "valor_pago" DECIMAL(10,2),
  "data_compra" TIMESTAMP
);

CREATE TABLE if not exists "resumo_vendas" (
  "evento_id" INT PRIMARY KEY REFERENCES "eventos" ("id"),
  "total_ingressos_vendidos" INT,
  "total_arrecadado" DECIMAL(10,2),
  "atualizado_em" TIMESTAMP DEFAULT now()
);
