CREATE TABLE "usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100),
  "sobrenome" varchar(100),
  "email" varchar(100) UNIQUE NOT NULL,
  "senha" varchar(255) NOT NULL,
  "cpf" varchar(14) UNIQUE,
  "data_nascimento" date,
  "genero" varchar(20),
  "criado_em" timestamp DEFAULT (now())
);

CREATE TABLE "organizadores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_entidade" varchar(100),
  "usuario_id" int
);

CREATE TABLE "eventos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar(100) NOT NULL,
  "descricao" text,
  "data" datetime,
  "local" varchar(255),
  "imagem_capa" varchar(255),
  "organizador_id" int,
  "criado_em" timestamp DEFAULT (now())
);

CREATE TABLE "ingressos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evento_id" int,
  "usuario_id" int,
  "tipo" varchar(50),
  "preco_pago" decimal(10,2),
  "status" enum(pendente,confirmado,cancelado) DEFAULT 'pendente',
  "data_compra" timestamp DEFAULT (now()),
  "codigo_ticket" varchar(50) UNIQUE
);

CREATE TABLE "pagamentos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ingresso_id" int,
  "valor" decimal(10,2),
  "forma_pagamento" enum(pix,cartao_credito,cartao_debito),
  "status" enum(pendente,aprovado,falhou) DEFAULT 'pendente',
  "data_pagamento" timestamp
);

CREATE TABLE "relatorio_vendas_evento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evento_id" int,
  "nome_comprador" varchar(100),
  "idade_comprador" int,
  "valor_pago" decimal(10,2),
  "data_compra" timestamp
);

CREATE TABLE "resumo_vendas" (
  "evento_id" int PRIMARY KEY,
  "total_ingressos_vendidos" int,
  "total_arrecadado" decimal(10,2),
  "atualizado_em" timestamp DEFAULT (now())
);

ALTER TABLE "organizadores" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "eventos" ADD FOREIGN KEY ("organizador_id") REFERENCES "organizadores" ("id");

ALTER TABLE "ingressos" ADD FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");

ALTER TABLE "ingressos" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "pagamentos" ADD FOREIGN KEY ("ingresso_id") REFERENCES "ingressos" ("id");

ALTER TABLE "relatorio_vendas_evento" ADD FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");

ALTER TABLE "resumo_vendas" ADD FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");
